import styled from "styled-components";

export default function Loading({ color }) {
    return (
        <LoadingGif>
            <Ball>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </Ball>
        </LoadingGif>
    );
}

const LoadingGif = styled.div`
    width: 100%;
    height: 100%;
    display: inline-block;
    overflow: hidden;
`;

const Ball = styled.div`
    width: 100%;
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: end;
    padding: 5px;
    gap: 12px;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */

    @keyframes bounce-effect {
        0%,
        100% {
            animation-timing-function: cubic-bezier(0, 0.45, 0.55, 0.9);
        }
        0% {
            transform: translate(0, 0);
        }
        50% {
            transform: translate(0, -32px);
            animation-timing-function: cubic-bezier(0, 0, 0.9, 0.55);
        }
        100% {
            transform: translate(0, 0);
        }
    }

    div {
        box-sizing: content-box;
        width: 12px;
        height: 12px;
        border-radius: 50%;
        background: var(--white);
        animation: bounce-effect 1s linear infinite;
    }

    div:nth-child(2){
        animation-delay: .2s;
    }

    div:nth-child(3){
        animation-delay: .4s;
    }

    div:nth-child(4){
        animation-delay: .6s;
    }
    
    /* generated by https://loading.io/ */
`;
